
export const UI_TEXT = {
  toggleTooltip: "开始反馈模式",
  resumeAnimations: "恢复动画",
  pauseAnimations: "暂停动画",
  hideMarkers: "隐藏标记",
  showMarkers: "显示标记",
  copyFeedback: "复制反馈",
  sendAnnotations: "发送反馈",
  clearAll: "全部清除",
  settings: "设置",
  exit: "退出",
  autoClear: "复制/发送后清除",
  autoClearTooltip: "复制后自动清除标记",
  outputDetail: "输出详情",
  outputDetailTooltip: "控制生成反馈的详细程度",
  minimal: "极简",
  compact: "紧凑",
  standard: "标准",
  detailed: "详细",
  forensic: "正常",
  reactMode: "React 组件检测",
  reactModeTooltip: "如何在 DOM 中识别 React 组件",
  webhookUrl: "Webhook URL",
  webhookUrlPlaceholder: "https://example.com/webhook",
  webhookUrlTooltip: "将反馈发送到此 URL (POST 请求)",
  annotationColor: "标记颜色",
  annotationColorTooltip: "标记的颜色",
  reactComponents: "React 组件",
  reactComponentsTooltip: "在标记中包含 React 组件名称",
  reactComponentsTooltipDisabled: "已禁用 — 生产构建会压缩组件名称，导致检测不可靠。请在开发环境中使用 localhost。",
  markerColor: "标记颜色",
  blockPageInteractions: "阻止页面交互",
  webhooks: "Webhooks",
  autoSend: "自动发送",
  webhookUrlDescription: "Webhook URL 将接收实时的标记变更和数据。"
};
